// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_midi

#ifndef UI_BOOTSCREEN_H
#define UI_BOOTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BootScreen
extern void ui_BootScreen_screen_init(void);
extern void ui_BootScreen_screen_destroy(void);
extern void ui_event_BootScreen(lv_event_t * e);
extern lv_obj_t * ui_BootScreen;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label36;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

