// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_drumpad

#ifndef UI_DRUMPADSCREEN_H
#define UI_DRUMPADSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DrumpadScreen
extern void ui_DrumpadScreen_screen_init(void);
extern void ui_DrumpadScreen_screen_destroy(void);
extern lv_obj_t * ui_DrumpadScreen;
extern lv_obj_t * ui_DContainer2;
//extern lv_obj_t * ui_DLabel3;
//extern void ui_event_MIDIEnabled(lv_event_t * e);
//extern lv_obj_t * ui_MIDIEnabled;
extern lv_obj_t * ui_DContainer3;
extern lv_obj_t * ui_OctaveDown;
extern lv_obj_t * ui_OctaveLabel;
extern lv_obj_t * ui_OctaveUp;
extern lv_obj_t * ui_DContainer;
extern lv_obj_t * ui_DButton1;
extern lv_obj_t * ui_DButton2;
extern lv_obj_t * ui_DButton3;
extern lv_obj_t * ui_DButton4;
extern lv_obj_t * ui_DButton5;
extern lv_obj_t * ui_DButton6;
extern lv_obj_t * ui_DButton7;
extern lv_obj_t * ui_DButton8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

