// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_drumpad

#include "../ui.h"

lv_obj_t * ui_DrumpadScreen = NULL;
lv_obj_t * ui_DContainer2 = NULL;
//lv_obj_t * ui_DLabel3 = NULL;
//lv_obj_t * ui_MIDIEnabled = NULL;
lv_obj_t * ui_DContainer3 = NULL;
lv_obj_t * ui_OctaveDown = NULL;
lv_obj_t * ui_OctaveLabel = NULL;
lv_obj_t * ui_OctaveUp = NULL;
lv_obj_t * ui_DContainer = NULL;
lv_obj_t * ui_DButton1 = NULL;
lv_obj_t * ui_DButton2 = NULL;
lv_obj_t * ui_DButton3 = NULL;
lv_obj_t * ui_DButton4 = NULL;
lv_obj_t * ui_DButton5 = NULL;
lv_obj_t * ui_DButton6 = NULL;
lv_obj_t * ui_DButton7 = NULL;
lv_obj_t * ui_DButton8 = NULL;

// MIDI drumpad configuration
static int current_octave = 4; // middle C = octave 4
static midi_cfg_t drum_cfg[8]; // user data for drum buttons
static const uint8_t drum_notes[8] = { 60, 62, 64, 65, 67, 69, 71, 72 }; // C4..C5

static uint8_t drum_note_to_midi(uint8_t drum_index) {
    return (current_octave * 12) + drum_notes[drum_index];
}

// Octave button callbacks
static void ui_event_OctaveDown(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    if(code != LV_EVENT_CLICKED) return;

    if(current_octave > 0) current_octave--; // prevent going below octave 0
    for(int i=0;i<8;i++) {
        drum_cfg[i].note = drum_note_to_midi(i); // update midi_cfg note
    }
    char buf[8];
    snprintf(buf, sizeof(buf), "Octave %d", current_octave);
    lv_label_set_text(ui_OctaveLabel, buf);
}

static void ui_event_OctaveUp(lv_event_t * e) {
    lv_event_code_t code = lv_event_get_code(e);
    if(code != LV_EVENT_CLICKED) return;

    if(current_octave < 9) current_octave++; // prevent going above octave 9
    for(int i=0;i<8;i++) {
        drum_cfg[i].note = drum_note_to_midi(i); // update midi_cfg note
    }
    char buf[8];
    snprintf(buf, sizeof(buf), "Octave %d", current_octave);
    lv_label_set_text(ui_OctaveLabel, buf);
}


// event funtions
//void ui_event_MIDIEnabled(lv_event_t * e)
//{
//    lv_event_code_t event_code = lv_event_get_code(e);
//    lv_obj_t * target = lv_event_get_target(e);
//
//    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
//        _ui_state_modify(ui_DButton8, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton7, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton6, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton5, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton4, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton3, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//        _ui_state_modify(ui_DButton1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
//    }
//    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
//        _ui_state_modify(ui_DButton8, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton7, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton6, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton5, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton4, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//        _ui_state_modify(ui_DButton1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
//    }
//}

// build funtions

void ui_DrumpadScreen_screen_init(void)
{
    ui_DrumpadScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DrumpadScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_DrumpadScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DrumpadScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER);

    ui_DContainer2 = lv_obj_create(ui_DrumpadScreen);
    lv_obj_remove_style_all(ui_DContainer2);
    lv_obj_set_width(ui_DContainer2, 400);
    lv_obj_set_height(ui_DContainer2, 100);
    lv_obj_set_align(ui_DContainer2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DContainer2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DContainer2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_DContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // I am removing this because it is causing too many issues, for some reason whenever the UI values update this switch changes style and causes CPU 0 to panic
    // literally no other switch does this but this one...

    //ui_DLabel3 = lv_label_create(ui_DContainer2);
    //lv_obj_set_width(ui_DLabel3, LV_SIZE_CONTENT);   /// 1
    //lv_obj_set_height(ui_DLabel3, LV_SIZE_CONTENT);    /// 1
    //lv_obj_set_align(ui_DLabel3, LV_ALIGN_CENTER);
    //lv_label_set_text(ui_DLabel3, "MIDI Enabled:");
    //lv_obj_set_style_text_font(ui_DLabel3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
//
    //ui_MIDIEnabled = lv_switch_create(ui_DContainer2);
    //lv_obj_set_width(ui_MIDIEnabled, 50);
    //lv_obj_set_height(ui_MIDIEnabled, 25);
    //lv_obj_set_align(ui_MIDIEnabled, LV_ALIGN_CENTER);

    ui_DContainer3 = lv_obj_create(ui_DrumpadScreen);
    lv_obj_remove_style_all(ui_DContainer3);
    lv_obj_set_width(ui_DContainer3, 1024);
    lv_obj_set_height(ui_DContainer3, 50);
    lv_obj_set_align(ui_DContainer3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DContainer3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DContainer3, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OctaveDown = lv_button_create(ui_DContainer3);
    lv_obj_set_width(ui_OctaveDown, 50);
    lv_obj_set_height(ui_OctaveDown, 50);
    lv_obj_set_align(ui_OctaveDown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OctaveDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OctaveDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OctaveDown, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OctaveDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_OctaveDown, &ui_img_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_OctaveDown, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_OctaveDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OctaveLabel = lv_label_create(ui_DContainer3);
    lv_obj_set_width(ui_OctaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OctaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_OctaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OctaveLabel, "Octave");
    lv_obj_set_style_text_font(ui_OctaveLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OctaveUp = lv_button_create(ui_DContainer3);
    lv_obj_set_width(ui_OctaveUp, 50);
    lv_obj_set_height(ui_OctaveUp, 50);
    lv_obj_set_align(ui_OctaveUp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OctaveUp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_OctaveUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OctaveUp, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OctaveUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_OctaveUp, &ui_img_right_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_OctaveUp, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_OctaveUp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DContainer = lv_obj_create(ui_DrumpadScreen);
    lv_obj_remove_style_all(ui_DContainer);
    lv_obj_set_width(ui_DContainer, 1024);
    lv_obj_set_height(ui_DContainer, 400);
    lv_obj_set_align(ui_DContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DContainer, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_DContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_DContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Create 8 drum buttons and assign midi_cfg_t
    lv_obj_t* drum_buttons[8] = {
        ui_DButton1 = lv_button_create(ui_DContainer),
        ui_DButton2 = lv_button_create(ui_DContainer),
        ui_DButton3 = lv_button_create(ui_DContainer),
        ui_DButton4 = lv_button_create(ui_DContainer),
        ui_DButton5 = lv_button_create(ui_DContainer),
        ui_DButton6 = lv_button_create(ui_DContainer),
        ui_DButton7 = lv_button_create(ui_DContainer),
        ui_DButton8 = lv_button_create(ui_DContainer)
    };

    for(int i=0;i<8;i++) {
        lv_obj_set_size(drum_buttons[i], 150, 150);
        lv_obj_add_flag(drum_buttons[i], LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);
        lv_obj_remove_flag(drum_buttons[i], LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_remove_state(drum_buttons[i], LV_STATE_DISABLED);
        lv_obj_set_style_bg_color(drum_buttons[i], lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
        drum_cfg[i].note = drum_notes[i];
        drum_cfg[i].channel = 0;
        lv_obj_add_event_cb(drum_buttons[i], ui_event_drum_pad, LV_EVENT_ALL, &drum_cfg[i]);
    }

    //lv_obj_add_event_cb(ui_MIDIEnabled, ui_event_MIDIEnabled, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OctaveDown, ui_event_OctaveDown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_OctaveUp, ui_event_OctaveUp, LV_EVENT_ALL, NULL);


    //midi_setup_DrumpadScreen(); // MIDI CC setup from midi_control.c

}

void ui_DrumpadScreen_screen_destroy(void)
{
    if(ui_DrumpadScreen) lv_obj_del(ui_DrumpadScreen);

    ui_DrumpadScreen = NULL;
    ui_DContainer2 = NULL;
    //ui_DLabel3 = NULL;
    //ui_MIDIEnabled = NULL;
    ui_DContainer3 = NULL;
    ui_OctaveDown = NULL;
    ui_OctaveLabel = NULL;
    ui_OctaveUp = NULL;
    ui_DContainer = NULL;
    ui_DButton1 = NULL;
    ui_DButton2 = NULL;
    ui_DButton3 = NULL;
    ui_DButton4 = NULL;
    ui_DButton5 = NULL;
    ui_DButton6 = NULL;
    ui_DButton7 = NULL;
    ui_DButton8 = NULL;

}
