// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_midi

#ifndef UI_EFFECTSSCREEN_H
#define UI_EFFECTSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EffectsScreen
extern void ui_EffectsScreen_screen_init(void);
extern void ui_EffectsScreen_screen_destroy(void);
extern lv_obj_t * ui_EffectsScreen;
extern lv_obj_t * ui_Container35;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label28;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_BitCrushSwitch;
extern lv_obj_t * ui_Container47;
extern lv_obj_t * ui_Container48;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_BitCrush;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_BulgeSwitch;
extern lv_obj_t * ui_Container49;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Bulge;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_VectorSwitch;
extern lv_obj_t * ui_Container50;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_VectorCancelling;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_SwirlSwitch;
extern lv_obj_t * ui_Container51;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Swirl;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_SmoothingSwitch;
extern lv_obj_t * ui_Container52;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Smoothing;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_WobbleSwitch;
extern lv_obj_t * ui_Container37;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_WobbleAmount;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_WobblePhase;
extern lv_obj_t * ui_Container28;
extern lv_obj_t * ui_DelaySwitch;
extern lv_obj_t * ui_Container45;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_DelayDecay;
extern lv_obj_t * ui_Container26;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_DelayLength;
extern lv_obj_t * ui_Container29;
extern lv_obj_t * ui_DashSwitch;
extern lv_obj_t * ui_Container53;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_DashLength;
extern lv_obj_t * ui_Container30;
extern lv_obj_t * ui_LuaSwitch;
extern lv_obj_t * ui_Container54;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_LuaEffect;
extern lv_obj_t * ui_Container33;
extern lv_obj_t * ui_TraceSwitch;
extern lv_obj_t * ui_Container46;
extern lv_obj_t * ui_Container27;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_TraceStart;
extern lv_obj_t * ui_Container31;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_TraceLength;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

