// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_midi

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_Container34 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Container32 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Frequency = NULL;
lv_obj_t * ui_Container38 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Perspective = NULL;
lv_obj_t * ui_Container39 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_FocalLength = NULL;
// event funtions
void ui_event_MainScreen(lv_event_t * e)
{
    bool hide_player = lv_obj_has_state(ui_HidePlayerSW, LV_STATE_CHECKED);
    bool flip_objs = lv_obj_has_state(ui_FlipGlobalObjsSW, LV_STATE_CHECKED);

    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        if (lv_obj_has_state(ui_HidePlayerSW, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_GlobalObjContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        } else {
            _ui_flag_modify(ui_GlobalObjContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        }

        if (lv_obj_has_state(ui_FlipGlobalObjsSW, LV_STATE_CHECKED)) {
            lv_obj_set_align(ui_GlobalObjContainer, LV_ALIGN_TOP_RIGHT);
            lv_obj_set_align(ui_GlobalSettingsContainer, LV_ALIGN_TOP_LEFT);
        } else {
            lv_obj_set_align(ui_GlobalObjContainer, LV_ALIGN_TOP_LEFT);
            lv_obj_set_align(ui_GlobalSettingsContainer, LV_ALIGN_TOP_RIGHT);
        }
        save_settings_objs(hide_player, flip_objs);

        // always unhide settings objects after bootscreen
        _ui_flag_modify(ui_GlobalSettingsContainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ModifyScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_ModifyScreen_screen_init);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_EffectsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_EffectsScreen_screen_init);
    }
}

// build funtions

void ui_MainScreen_screen_init(void)
{
    
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MainScreen, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_MainScreen, LV_DIR_VER);
    lv_obj_set_flex_flow(ui_MainScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_MainScreen, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);

    ui_Container34 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container34);
    lv_obj_set_width(ui_Container34, 1024);
    lv_obj_set_height(ui_Container34, 70);
    lv_obj_set_align(ui_Container34, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container34, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container34, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END);
    lv_obj_remove_flag(ui_Container34, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_button_create(ui_Container34);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button2, &ui_img_arrow_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button2, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button2, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Container34);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Frequency");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_button_create(ui_Container34);
    lv_obj_set_width(ui_Button1, 80);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button1, &ui_img_1101766569, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Button1, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 155, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container32 = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_Container32);
    lv_obj_set_width(ui_Container32, 1024);
    lv_obj_set_height(ui_Container32, 520);
    lv_obj_set_align(ui_Container32, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container32, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container32, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container32, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Container32);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 1024);
    lv_obj_set_height(ui_Container1, 70);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Frequency");

    ui_Frequency = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_Frequency, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Frequency) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Frequency, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Frequency, 500);
    lv_obj_set_height(ui_Frequency, 10);
    lv_obj_set_align(ui_Frequency, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Frequency, lv_color_hex(0x2ABE44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Frequency, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Frequency, lv_color_hex(0x177023), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Frequency, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Frequency, lv_color_hex(0x2ABE44), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Frequency, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Frequency, lv_color_hex(0x177023), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Frequency, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Frequency, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Frequency,
                                                                                                lv_obj_get_style_pad_right(ui_Frequency, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container38 = lv_obj_create(ui_Container32);
    lv_obj_remove_style_all(ui_Container38);
    lv_obj_set_width(ui_Container38, 1024);
    lv_obj_set_height(ui_Container38, 70);
    lv_obj_set_align(ui_Container38, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container38, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container38, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label30 = lv_label_create(ui_Container38);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "Perspective");

    ui_Perspective = lv_slider_create(ui_Container38);
    lv_slider_set_value(ui_Perspective, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Perspective) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Perspective, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Perspective, 500);
    lv_obj_set_height(ui_Perspective, 10);
    lv_obj_set_align(ui_Perspective, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Perspective, lv_color_hex(0x2ABE44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Perspective, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Perspective, lv_color_hex(0x2ABE44), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Perspective, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Perspective, lv_color_hex(0x177023), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Perspective, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Perspective, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Perspective,
                                                                                                  lv_obj_get_style_pad_right(ui_Perspective, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Container39 = lv_obj_create(ui_Container32);
    lv_obj_remove_style_all(ui_Container39);
    lv_obj_set_width(ui_Container39, 1024);
    lv_obj_set_height(ui_Container39, 70);
    lv_obj_set_align(ui_Container39, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container39, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container39, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Container39);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Focal length");

    ui_FocalLength = lv_slider_create(ui_Container39);
    lv_slider_set_value(ui_FocalLength, 20, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_FocalLength) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_FocalLength, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_FocalLength, 500);
    lv_obj_set_height(ui_FocalLength, 10);
    lv_obj_set_align(ui_FocalLength, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FocalLength, lv_color_hex(0x2ABE44), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FocalLength, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FocalLength, lv_color_hex(0x2ABE44), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FocalLength, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_FocalLength, lv_color_hex(0x177023), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FocalLength, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_FocalLength, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_FocalLength,
                                                                                                  lv_obj_get_style_pad_right(ui_FocalLength, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_add_event_cb(ui_MainScreen, ui_event_MainScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

    // init MIDI CC inputs
    midi_setup_MainScreen();

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_Container34 = NULL;
    ui_Button2 = NULL;
    ui_Label25 = NULL;
    ui_Button1 = NULL;
    ui_Container32 = NULL;
    ui_Container1 = NULL;
    ui_Label1 = NULL;
    ui_Frequency = NULL;
    ui_Container38 = NULL;
    ui_Label30 = NULL;
    ui_Perspective = NULL;
    ui_Container39 = NULL;
    ui_Label31 = NULL;
    ui_FocalLength = NULL;

}
