// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_midi

#ifndef UI_MODIFYSCREEN_H
#define UI_MODIFYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ModifyScreen
extern void ui_ModifyScreen_screen_init(void);
extern void ui_ModifyScreen_screen_destroy(void);
extern lv_obj_t * ui_ModifyScreen;
extern lv_obj_t * ui_Container36;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label29;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Container44;
extern lv_obj_t * ui_ScaleSwitch;
extern lv_obj_t * ui_ScaleContainer;
extern lv_obj_t * ui_Container40;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_ScaleX;
extern lv_obj_t * ui_Container41;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_ScaleY;
extern lv_obj_t * ui_Container42;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_ScaleZ;
extern lv_obj_t * ui_Container43;
extern lv_obj_t * ui_DistortSwitch;
extern lv_obj_t * ui_DistortContainer;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_DistortX;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_DistortY;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_DistortZ;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_RotateSwitch;
extern lv_obj_t * ui_RotateContainer;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_RotateX;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_RotateY;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_RotateZ;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_TranslateSwitch;
extern lv_obj_t * ui_TranslateContainer;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_TranslateX;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_TranslateY;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_TranslateZ;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_RippleSwitch;
extern lv_obj_t * ui_RippleContainer;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_RippleDepth;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_RipplePhase;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_RippleAmount;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

