// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_settings

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingsScreen;
extern lv_obj_t * ui_SettingsHeader;
extern lv_obj_t * ui_SLabel2;
extern lv_obj_t * ui_SettingsScontainer;
extern void ui_event_DeviceConfig(lv_event_t * e);
extern lv_obj_t * ui_DeviceConfig;
extern lv_obj_t * ui_SLabel21;
extern void ui_event_MIDIConfig(lv_event_t * e);
extern lv_obj_t * ui_MIDIConfig;
extern lv_obj_t * ui_SLabel1;
extern void ui_event_About(lv_event_t * e);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_SLabel25;
extern lv_obj_t * ui_DeviceScontainer;
extern void ui_event_DisplaySettings(lv_event_t * e);
extern lv_obj_t * ui_DisplaySettings;
extern lv_obj_t * ui_SLabel34;
extern void ui_event_ObjSettings(lv_event_t * e);
extern lv_obj_t * ui_ObjSettings;
extern lv_obj_t * ui_SLabel3;
extern void ui_event_Return(lv_event_t * e);
extern lv_obj_t * ui_Return;
extern lv_obj_t * ui_SLabel40;
extern lv_obj_t * ui_DisplayScontainer;
extern lv_obj_t * ui_SLabel36;
extern lv_obj_t * ui_DisplayBrightness;
extern void ui_event_Return_2(lv_event_t * e);
extern lv_obj_t * ui_Return_2;
extern lv_obj_t * ui_SLabel41;
extern lv_obj_t * ui_ObjScontainer;
extern lv_obj_t * ui_Scontainer5;
extern lv_obj_t * ui_SLabel4;
extern lv_obj_t * ui_HidePlayerSW;
extern lv_obj_t * ui_SLabelFlip;
extern lv_obj_t * ui_FlipGlobalObjsSW;
extern void ui_event_Return_1(lv_event_t * e);
extern lv_obj_t * ui_Return_1;
extern lv_obj_t * ui_SLabel5;
extern lv_obj_t * ui_MIDIScontainer;
extern lv_obj_t * ui_Scontainer4;
extern lv_obj_t * ui_SLabel42;
extern lv_obj_t * ui_Dropdown1;
extern lv_obj_t * ui_SLabelUpdate;
extern void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_SLabel44;
extern lv_obj_t * ui_AboutScontainer;
extern lv_obj_t * ui_Scontainer6;
extern lv_obj_t * ui_S_image1;
extern lv_obj_t * ui_SLabel6;
extern lv_obj_t * ui_SLabel7;
extern lv_obj_t * ui_SLabel8;
extern lv_obj_t * ui_SLabel10;
extern lv_obj_t * ui_SLabel9;
extern void ui_event_Return2(lv_event_t * e);
extern lv_obj_t * ui_Return2;
extern lv_obj_t * ui_SLabel51;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

