// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: osci_render_settings

#include "../ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_SettingsHeader = NULL;
lv_obj_t * ui_SLabel2 = NULL;
lv_obj_t * ui_SettingsScontainer = NULL;
lv_obj_t * ui_DeviceConfig = NULL;
lv_obj_t * ui_SLabel21 = NULL;
lv_obj_t * ui_MIDIConfig = NULL;
lv_obj_t * ui_SLabel1 = NULL;
lv_obj_t * ui_About = NULL;
lv_obj_t * ui_SLabel25 = NULL;
lv_obj_t * ui_DeviceScontainer = NULL;
lv_obj_t * ui_DisplaySettings = NULL;
lv_obj_t * ui_SLabel34 = NULL;
lv_obj_t * ui_ObjSettings = NULL;
lv_obj_t * ui_SLabel3 = NULL;
lv_obj_t * ui_Return = NULL;
lv_obj_t * ui_SLabel40 = NULL;
lv_obj_t * ui_DisplayScontainer = NULL;
lv_obj_t * ui_SLabel36 = NULL;
lv_obj_t * ui_DisplayBrightness = NULL;
lv_obj_t * ui_Return_2 = NULL;
lv_obj_t * ui_SLabel41 = NULL;
lv_obj_t * ui_ObjScontainer = NULL;
lv_obj_t * ui_Scontainer5 = NULL;
lv_obj_t * ui_SLabel4 = NULL;
lv_obj_t * ui_HidePlayerSW = NULL;
lv_obj_t * ui_SLabelFlip = NULL;
lv_obj_t * ui_FlipGlobalObjsSW = NULL;
lv_obj_t * ui_Return_1 = NULL;
lv_obj_t * ui_SLabel5 = NULL;
lv_obj_t * ui_MIDIScontainer = NULL;
lv_obj_t * ui_Scontainer4 = NULL;
lv_obj_t * ui_SLabel42 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_SLabelUpdate = NULL;
lv_obj_t * ui_Button24 = NULL;
lv_obj_t * ui_SLabel44 = NULL;
lv_obj_t * ui_AboutScontainer = NULL;
lv_obj_t * ui_Scontainer6 = NULL;
lv_obj_t * ui_S_image1 = NULL;
lv_obj_t * ui_SLabel6 = NULL;
lv_obj_t * ui_SLabel7 = NULL;
lv_obj_t * ui_SLabel8 = NULL;
lv_obj_t * ui_SLabel10 = NULL;
lv_obj_t * ui_SLabel9 = NULL;
lv_obj_t * ui_Return2 = NULL;
lv_obj_t * ui_SLabel51 = NULL;
// event funtions
void ui_event_DeviceConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_MIDIConfig(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_MIDIScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_About(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_AboutScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SettingsHeader, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_DisplaySettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_DisplayScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_ObjSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ObjScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Return(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Return_2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_DisplayScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Return_1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ObjScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button24(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_MIDIScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Return2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_AboutScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_SettingsScontainer, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_SettingsHeader, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_brightness_slider(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_VALUE_CHANGED) return;

    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);  // 0–100 range
    uint8_t brightness = (val == 0) ? 1 : val; // if slider value = 0, change value to 1 so brightness isn't fully off
    bsp_display_brightness_set(brightness);
    save_settings_ui(brightness);
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_SettingsScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_SettingsHeader = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_SettingsHeader);
    lv_obj_set_width(ui_SettingsHeader, 1024);
    lv_obj_set_height(ui_SettingsHeader, 80);
    lv_obj_set_align(ui_SettingsHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_SettingsHeader, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SettingsHeader, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SettingsHeader, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_SettingsHeader, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel2 = lv_label_create(ui_SettingsHeader);
    lv_obj_set_width(ui_SLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel2, "Settings");
    lv_obj_set_style_text_color(ui_SLabel2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_SettingsScontainer);
    lv_obj_set_width(ui_SettingsScontainer, 1024);
    lv_obj_set_height(ui_SettingsScontainer, 400);
    lv_obj_set_align(ui_SettingsScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DeviceConfig = lv_button_create(ui_SettingsScontainer);
    lv_obj_set_width(ui_DeviceConfig, 1024);
    lv_obj_set_height(ui_DeviceConfig, 75);
    lv_obj_set_align(ui_DeviceConfig, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DeviceConfig, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DeviceConfig, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeviceConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DeviceConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DeviceConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DeviceConfig, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DeviceConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DeviceConfig, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DeviceConfig, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DeviceConfig, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DeviceConfig, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel21 = lv_label_create(ui_DeviceConfig);
    lv_obj_set_width(ui_SLabel21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel21, "Device");
    lv_obj_set_style_text_font(ui_SLabel21, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MIDIConfig = lv_button_create(ui_SettingsScontainer);
    lv_obj_set_width(ui_MIDIConfig, 1024);
    lv_obj_set_height(ui_MIDIConfig, 75);
    lv_obj_set_align(ui_MIDIConfig, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MIDIConfig, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_MIDIConfig, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_MIDIConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MIDIConfig, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MIDIConfig, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MIDIConfig, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MIDIConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MIDIConfig, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MIDIConfig, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MIDIConfig, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_MIDIConfig, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel1 = lv_label_create(ui_MIDIConfig);
    lv_obj_set_width(ui_SLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel1, "MIDI");
    lv_obj_set_style_text_font(ui_SLabel1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_About = lv_button_create(ui_SettingsScontainer);
    lv_obj_set_width(ui_About, 1024);
    lv_obj_set_height(ui_About, 75);
    lv_obj_set_align(ui_About, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_About, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_About, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_About, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_About, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_About, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_About, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel25 = lv_label_create(ui_About);
    lv_obj_set_width(ui_SLabel25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel25, "About");
    lv_obj_set_style_text_font(ui_SLabel25, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_DeviceScontainer);
    lv_obj_set_width(ui_DeviceScontainer, 1024);
    lv_obj_set_height(ui_DeviceScontainer, 520);
    lv_obj_set_align(ui_DeviceScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DeviceScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DeviceScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DeviceScontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DeviceScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DisplaySettings = lv_button_create(ui_DeviceScontainer);
    lv_obj_set_width(ui_DisplaySettings, 1024);
    lv_obj_set_height(ui_DisplaySettings, 75);
    lv_obj_set_align(ui_DisplaySettings, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DisplaySettings, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DisplaySettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisplaySettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_DisplaySettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DisplaySettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DisplaySettings, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplaySettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DisplaySettings, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DisplaySettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DisplaySettings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_DisplaySettings, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel34 = lv_label_create(ui_DisplaySettings);
    lv_obj_set_width(ui_SLabel34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel34, "Display");
    lv_obj_set_style_text_font(ui_SLabel34, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ObjSettings = lv_button_create(ui_DeviceScontainer);
    lv_obj_set_width(ui_ObjSettings, 1024);
    lv_obj_set_height(ui_ObjSettings, 75);
    lv_obj_set_align(ui_ObjSettings, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ObjSettings, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ObjSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ObjSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ObjSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ObjSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ObjSettings, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ObjSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ObjSettings, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ObjSettings, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ObjSettings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ObjSettings, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel3 = lv_label_create(ui_ObjSettings);
    lv_obj_set_width(ui_SLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel3, "Objects");
    lv_obj_set_style_text_font(ui_SLabel3, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Return = lv_button_create(ui_DeviceScontainer);
    lv_obj_set_width(ui_Return, 120);
    lv_obj_set_height(ui_Return, 50);
    lv_obj_set_align(ui_Return, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Return, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Return, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Return, lv_color_hex(0x38A3A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Return, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel40 = lv_label_create(ui_Return);
    lv_obj_set_width(ui_SLabel40, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel40, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel40, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel40, "Return");

    ui_DisplayScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_DisplayScontainer);
    lv_obj_set_width(ui_DisplayScontainer, 1024);
    lv_obj_set_height(ui_DisplayScontainer, 400);
    lv_obj_set_align(ui_DisplayScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DisplayScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DisplayScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_DisplayScontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_DisplayScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SLabel36 = lv_label_create(ui_DisplayScontainer);
    lv_obj_set_width(ui_SLabel36, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel36, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel36, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel36, "Brightness");
    lv_obj_set_style_text_font(ui_SLabel36, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DisplayBrightness = lv_slider_create(ui_DisplayScontainer);
    lv_slider_set_value(ui_DisplayBrightness, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_DisplayBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_DisplayBrightness, 0,
                                                                                                      LV_ANIM_OFF);
    lv_obj_set_width(ui_DisplayBrightness, 400);
    lv_obj_set_height(ui_DisplayBrightness, 14);
    lv_obj_set_align(ui_DisplayBrightness, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_DisplayBrightness, lv_color_hex(0x22577A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayBrightness, 55, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DisplayBrightness, lv_color_hex(0x22577A), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayBrightness, 155, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_DisplayBrightness, lv_color_hex(0x38A3A5), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DisplayBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DisplayBrightness, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DisplayBrightness,
                                                                                                        lv_obj_get_style_pad_right(ui_DisplayBrightness, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Return_2 = lv_button_create(ui_DisplayScontainer);
    lv_obj_set_width(ui_Return_2, 120);
    lv_obj_set_height(ui_Return_2, 50);
    lv_obj_set_align(ui_Return_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Return_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Return_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Return_2, lv_color_hex(0x38A3A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Return_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel41 = lv_label_create(ui_Return_2);
    lv_obj_set_width(ui_SLabel41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel41, "Return");

    ui_ObjScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_ObjScontainer);
    lv_obj_set_width(ui_ObjScontainer, 1024);
    lv_obj_set_height(ui_ObjScontainer, 400);
    lv_obj_set_align(ui_ObjScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ObjScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ObjScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ObjScontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_ObjScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scontainer5 = lv_obj_create(ui_ObjScontainer);
    lv_obj_remove_style_all(ui_Scontainer5);
    lv_obj_set_width(ui_Scontainer5, 300);
    lv_obj_set_height(ui_Scontainer5, 250);
    lv_obj_set_align(ui_Scontainer5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Scontainer5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Scontainer5, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);
    lv_obj_remove_flag(ui_Scontainer5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SLabel4 = lv_label_create(ui_Scontainer5);
    lv_obj_set_width(ui_SLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel4, "Hide global player:");
    lv_obj_set_style_text_font(ui_SLabel4, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HidePlayerSW = lv_switch_create(ui_Scontainer5);
    lv_obj_set_width(ui_HidePlayerSW, 50);
    lv_obj_set_height(ui_HidePlayerSW, 25);
    lv_obj_set_align(ui_HidePlayerSW, LV_ALIGN_CENTER);

    ui_SLabelFlip = lv_label_create(ui_Scontainer5);
    lv_obj_set_width(ui_SLabelFlip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabelFlip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabelFlip, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabelFlip, "Flip global objects:");
    lv_obj_set_style_text_font(ui_SLabelFlip, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FlipGlobalObjsSW = lv_switch_create(ui_Scontainer5);
    lv_obj_set_width(ui_FlipGlobalObjsSW, 50);
    lv_obj_set_height(ui_FlipGlobalObjsSW, 25);
    lv_obj_set_align(ui_FlipGlobalObjsSW, LV_ALIGN_CENTER);

    ui_Return_1 = lv_button_create(ui_ObjScontainer);
    lv_obj_set_width(ui_Return_1, 120);
    lv_obj_set_height(ui_Return_1, 50);
    lv_obj_set_align(ui_Return_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Return_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Return_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Return_1, lv_color_hex(0x38A3A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Return_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel5 = lv_label_create(ui_Return_1);
    lv_obj_set_width(ui_SLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel5, "Return");

    ui_MIDIScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_MIDIScontainer);
    lv_obj_set_width(ui_MIDIScontainer, 1024);
    lv_obj_set_height(ui_MIDIScontainer, 500);
    lv_obj_set_align(ui_MIDIScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MIDIScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MIDIScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_MIDIScontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_MIDIScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scontainer4 = lv_obj_create(ui_MIDIScontainer);
    lv_obj_remove_style_all(ui_Scontainer4);
    lv_obj_set_width(ui_Scontainer4, 300);
    lv_obj_set_height(ui_Scontainer4, 200);
    lv_obj_set_align(ui_Scontainer4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Scontainer4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Scontainer4, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Scontainer4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SLabel42 = lv_label_create(ui_Scontainer4);
    lv_obj_set_width(ui_SLabel42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel42, "MIDI Connection Method:");
    lv_obj_set_style_text_font(ui_SLabel42, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Dropdown1 = lv_dropdown_create(ui_Scontainer4);
    lv_dropdown_set_options(ui_Dropdown1, "USB\nWireless");
    lv_obj_set_width(ui_Dropdown1, 200);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SLabelUpdate = lv_label_create(ui_Scontainer4);
    lv_obj_set_width(ui_SLabelUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabelUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabelUpdate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabelUpdate, "This has not been implemented yet, sorry :(");
    lv_obj_set_style_text_font(ui_SLabelUpdate, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_button_create(ui_MIDIScontainer);
    lv_obj_set_width(ui_Button24, 120);
    lv_obj_set_height(ui_Button24, 50);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button24, lv_color_hex(0x38A3A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel44 = lv_label_create(ui_Button24);
    lv_obj_set_width(ui_SLabel44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel44, "Return");

    ui_AboutScontainer = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_AboutScontainer);
    lv_obj_set_width(ui_AboutScontainer, 1024);
    lv_obj_set_height(ui_AboutScontainer, 550);
    lv_obj_set_align(ui_AboutScontainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutScontainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AboutScontainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_AboutScontainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_AboutScontainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Scontainer6 = lv_obj_create(ui_AboutScontainer);
    lv_obj_remove_style_all(ui_Scontainer6);
    lv_obj_set_width(ui_Scontainer6, 1024);
    lv_obj_set_height(ui_Scontainer6, 450);
    lv_obj_set_align(ui_Scontainer6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Scontainer6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Scontainer6, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Scontainer6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_S_image1 = lv_image_create(ui_Scontainer6);
    lv_image_set_src(ui_S_image1, &ui_img_1031218279);
    lv_obj_set_width(ui_S_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_S_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_S_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_S_image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_S_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_S_image1, 156);

    ui_SLabel6 = lv_label_create(ui_Scontainer6);
    lv_obj_set_width(ui_SLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel6, "Virtual MIDI Controller");
    lv_obj_set_style_text_color(ui_SLabel6, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel7 = lv_label_create(ui_Scontainer6);
    lv_obj_set_width(ui_SLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel7, "Created by: https://github.com/oldmate6288");
    lv_obj_set_style_text_color(ui_SLabel7, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel7, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel8 = lv_label_create(ui_Scontainer6);
    lv_obj_set_width(ui_SLabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel8, "osci-render:");
    lv_obj_set_style_text_color(ui_SLabel8, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel10 = lv_label_create(ui_Scontainer6);
    lv_obj_set_width(ui_SLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel10, "Created by: James H Ball");
    lv_obj_set_style_text_color(ui_SLabel10, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel10, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel9 = lv_label_create(ui_Scontainer6);
    lv_obj_set_width(ui_SLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel9, "https://osci-render.com/");
    lv_obj_set_style_text_color(ui_SLabel9, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SLabel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SLabel9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Return2 = lv_button_create(ui_AboutScontainer);
    lv_obj_set_width(ui_Return2, 120);
    lv_obj_set_height(ui_Return2, 50);
    lv_obj_set_align(ui_Return2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Return2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Return2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Return2, lv_color_hex(0x38A3A5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Return2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SLabel51 = lv_label_create(ui_Return2);
    lv_obj_set_width(ui_SLabel51, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SLabel51, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SLabel51, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SLabel51, "Return");

    lv_obj_add_event_cb(ui_DeviceConfig, ui_event_DeviceConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MIDIConfig, ui_event_MIDIConfig, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_About, ui_event_About, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DisplaySettings, ui_event_DisplaySettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ObjSettings, ui_event_ObjSettings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Return, ui_event_Return, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Return_2, ui_event_Return_2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Return_1, ui_event_Return_1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Return2, ui_event_Return2, LV_EVENT_ALL, NULL);

    lv_event_cb_t Bright_cb = ui_event_brightness_slider;
    lv_obj_add_event_cb(ui_DisplayBrightness, Bright_cb, LV_EVENT_VALUE_CHANGED, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_SettingsHeader = NULL;
    ui_SLabel2 = NULL;
    ui_SettingsScontainer = NULL;
    ui_DeviceConfig = NULL;
    ui_SLabel21 = NULL;
    ui_MIDIConfig = NULL;
    ui_SLabel1 = NULL;
    ui_About = NULL;
    ui_SLabel25 = NULL;
    ui_DeviceScontainer = NULL;
    ui_DisplaySettings = NULL;
    ui_SLabel34 = NULL;
    ui_ObjSettings = NULL;
    ui_SLabel3 = NULL;
    ui_Return = NULL;
    ui_SLabel40 = NULL;
    ui_DisplayScontainer = NULL;
    ui_SLabel36 = NULL;
    ui_DisplayBrightness = NULL;
    ui_Return_2 = NULL;
    ui_SLabel41 = NULL;
    ui_ObjScontainer = NULL;
    ui_Scontainer5 = NULL;
    ui_SLabel4 = NULL;
    ui_HidePlayerSW = NULL;
    ui_SLabelFlip = NULL;
    ui_FlipGlobalObjsSW = NULL;
    ui_Return_1 = NULL;
    ui_SLabel5 = NULL;
    ui_MIDIScontainer = NULL;
    ui_Scontainer4 = NULL;
    ui_SLabel42 = NULL;
    ui_Dropdown1 = NULL;
    ui_SLabelUpdate = NULL;
    ui_Button24 = NULL;
    ui_SLabel44 = NULL;
    ui_AboutScontainer = NULL;
    ui_Scontainer6 = NULL;
    ui_S_image1 = NULL;
    ui_SLabel6 = NULL;
    ui_SLabel7 = NULL;
    ui_SLabel8 = NULL;
    ui_SLabel10 = NULL;
    ui_SLabel9 = NULL;
    ui_Return2 = NULL;
    ui_SLabel51 = NULL;

}
